apiVersion: v1
kind: Pod
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  containers:
    - name: angular-container
      image: dpicuasi/work-schedule-board:ckad
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Puedes cambiar el puerto si está ocupado
